Update workflows

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -60,133 +60,133 @@ jobs:
         run: |
           rm -rf target/$target/debian
 
-  openwrt:
-    name: OpenWrt Package
-    runs-on: ubuntu-20.04
-    needs: [ linux ]
-    environment: OpenWrt
-    strategy:
-      fail-fast: false
-      matrix:
-        target:
-          - arch: "aarch64_generic"
-            sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/rockchip/armv8/openwrt-sdk-22.03.2-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
-          - arch: "aarch64_cortex-a53"
-            sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/bcm27xx/bcm2710/openwrt-sdk-22.03.2-bcm27xx-bcm2710_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
-          - arch: "aarch64_cortex-a72"
-            sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/bcm27xx/bcm2711/openwrt-sdk-22.03.2-bcm27xx-bcm2711_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
-          - arch: "x86_64"
-            sdk: "https://downloads.openwrt.org/releases/18.06.9/targets/x86/64/openwrt-sdk-18.06.9-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz"
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install build requirements
-        run: |
-          set -e
-          sudo apt-get update
-          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
-          gettext git java-propose-classpath libelf-dev libncurses5-dev \
-          libncursesw5-dev libssl-dev python2.7-dev python3 unzip wget \
-          python3-distutils python3-setuptools python3-dev rsync subversion \
-          swig time xsltproc zlib1g-dev
-      - name: Install OpenWrt SDK
-        run: |
-          set -e
-          wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
-          xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
-          mv -f openwrt-sdk-* openwrt-sdk
-      - name: Build Package
-        run: |
-          set -e
-          echo "src-link thunder $GITHUB_WORKSPACE/openwrt" > openwrt-sdk/feeds.conf
-          echo 'CONFIG_PACKAGE_thunder=y
-          CONFIG_PACKAGE_luci-app-thunder=y
-          ' >> openwrt-sdk/.config
-          cd openwrt-sdk
-          cat feeds.conf.default >> feeds.conf
-          cat feeds.conf
+  # openwrt:
+  #   name: OpenWrt Package
+  #   runs-on: ubuntu-20.04
+  #   needs: [ linux ]
+  #   environment: OpenWrt
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       target:
+  #         - arch: "aarch64_generic"
+  #           sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/rockchip/armv8/openwrt-sdk-22.03.2-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
+  #         - arch: "aarch64_cortex-a53"
+  #           sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/bcm27xx/bcm2710/openwrt-sdk-22.03.2-bcm27xx-bcm2710_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
+  #         - arch: "aarch64_cortex-a72"
+  #           sdk: "https://downloads.openwrt.org/releases/22.03.2/targets/bcm27xx/bcm2711/openwrt-sdk-22.03.2-bcm27xx-bcm2711_gcc-11.2.0_musl.Linux-x86_64.tar.xz"
+  #         - arch: "x86_64"
+  #           sdk: "https://downloads.openwrt.org/releases/18.06.9/targets/x86/64/openwrt-sdk-18.06.9-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz"
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Install build requirements
+  #       run: |
+  #         set -e
+  #         sudo apt-get update
+  #         sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
+  #         gettext git java-propose-classpath libelf-dev libncurses5-dev \
+  #         libncursesw5-dev libssl-dev python2.7-dev python3 unzip wget \
+  #         python3-distutils python3-setuptools python3-dev rsync subversion \
+  #         swig time xsltproc zlib1g-dev
+  #     - name: Install OpenWrt SDK
+  #       run: |
+  #         set -e
+  #         wget -O openwrt-sdk.tar.xz ${{ matrix.target.sdk }}
+  #         xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
+  #         mv -f openwrt-sdk-* openwrt-sdk
+  #     - name: Build Package
+  #       run: |
+  #         set -e
+  #         echo "src-link thunder $GITHUB_WORKSPACE/openwrt" > openwrt-sdk/feeds.conf
+  #         echo 'CONFIG_PACKAGE_thunder=y
+  #         CONFIG_PACKAGE_luci-app-thunder=y
+  #         ' >> openwrt-sdk/.config
+  #         cd openwrt-sdk
+  #         cat feeds.conf.default >> feeds.conf
+  #         cat feeds.conf
 
-          ./scripts/feeds update -a > /dev/null
-          make defconfig
+  #         ./scripts/feeds update -a > /dev/null
+  #         make defconfig
 
-          ./scripts/feeds install -d y -f -a
-          make package/thunder/compile V=s
-          make package/luci-app-thunder/compile V=s
-          tree bin/packages/
-      - name: Archive package
-        uses: actions/upload-artifact@v3
-        with:
-          name: thunder-launcher-${{ matrix.target.arch }}
-          path: openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/thunder*.ipk
-          if-no-files-found: error
-      - name: Archive luci packages
-        if: ${{ matrix.target.arch == 'x86_64' }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: thunder-launcher-luci-${{ matrix.target.arch }}
-          path: openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/luci-*.ipk
-          if-no-files-found: error
-      - name: Upload package to GitHub Release
-        uses: softprops/action-gh-release@v1
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          token: ${{ secrets.TOKEN }}
-          files: |
-            openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/thunder*.ipk
-          generate_release_notes: true
-      - name: Upload luci packages to GitHub Release
-        uses: softprops/action-gh-release@v1
-        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.target.arch == 'x86_64' }}
-        with:
-          token: ${{ secrets.TOKEN }}
-          files: |
-            openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/luci-*.ipk
-          generate_release_notes: true
+  #         ./scripts/feeds install -d y -f -a
+  #         make package/thunder/compile V=s
+  #         make package/luci-app-thunder/compile V=s
+  #         tree bin/packages/
+  #     - name: Archive package
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: thunder-launcher-${{ matrix.target.arch }}
+  #         path: openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/thunder*.ipk
+  #         if-no-files-found: error
+  #     - name: Archive luci packages
+  #       if: ${{ matrix.target.arch == 'x86_64' }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: thunder-launcher-luci-${{ matrix.target.arch }}
+  #         path: openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/luci-*.ipk
+  #         if-no-files-found: error
+  #     - name: Upload package to GitHub Release
+  #       uses: softprops/action-gh-release@v1
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       with:
+  #         token: ${{ secrets.TOKEN }}
+  #         files: |
+  #           openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/thunder*.ipk
+  #         generate_release_notes: true
+  #     - name: Upload luci packages to GitHub Release
+  #       uses: softprops/action-gh-release@v1
+  #       if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.target.arch == 'x86_64' }}
+  #       with:
+  #         token: ${{ secrets.TOKEN }}
+  #         files: |
+  #           openwrt-sdk/bin/packages/${{ matrix.target.arch }}/thunder/luci-*.ipk
+  #         generate_release_notes: true
 
-  docker:
-    name: Build Docker Image
-    runs-on: ubuntu-latest
-    needs: [ linux ]
-    environment: Docker
-    steps:
-      - uses: actions/checkout@v3
+  # docker:
+  #   name: Build Docker Image
+  #   runs-on: ubuntu-latest
+  #   needs: [ linux ]
+  #   environment: Docker
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v2
         
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v2
 
-      - name: Get tag
-        if: startsWith(github.ref, 'refs/tags/')
-        id: tag
-        uses: dawidd6/action-get-tag@v1
-        with:
-          strip_v: true
+  #     - name: Get tag
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       id: tag
+  #       uses: dawidd6/action-get-tag@v1
+  #       with:
+  #         strip_v: true
 
-      - name: Login to DockerHub
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+  #     - name: Login to DockerHub
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_TOKEN }}
 
-      - name: Login to GitHub Container Registry
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.TOKEN }}
+  #     - name: Login to GitHub Container Registry
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       uses: docker/login-action@v2
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.TOKEN }}
             
-      - name: Build and push
-        if: startsWith(github.ref, 'refs/tags/')
-        run: |
-          tag=${{ steps.tag.outputs.tag }} bash +x build_docker.sh
+  #     - name: Build and push
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       run: |
+  #         tag=${{ steps.tag.outputs.tag }} bash +x build_docker.sh
 
-      - name: Docker Hub Description
-        if: startsWith(github.ref, 'refs/tags/')
-        uses: peter-evans/dockerhub-description@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
-          repository: gngpp/xunlei
+  #     - name: Docker Hub Description
+  #       if: startsWith(github.ref, 'refs/tags/')
+  #       uses: peter-evans/dockerhub-description@v3
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_TOKEN }}
+  #         repository: gngpp/xunlei
